# Generated by Django 3.2.6 on 2021-08-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_peopleinfo_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='readcound',
            new_name='readcount',
        ),
    ]
